# -*- coding: utf-8 -*-
"""Entrada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11aWiPEvV2l0j4S1pYiXHIaIgZqAVRGD-
"""

def obtener_numero(mensaje):
    while True:
        try:
            return float(input(mensaje))
        except ValueError:
            print("Error: Debe ingresar un valor numérico.")

def ingresar_matriz():
    print("\nConfiguración de la matriz:")
    filas = int(obtener_numero("Ingrese el número de filas: "))
    columnas = int(obtener_numero("Ingrese el número de columnas: "))

    matriz = []
    for i in range(filas):
        fila = []
        for j in range(columnas):
            valor = obtener_numero(f"Elemento [{i+1}][{j+1}]: ")
            fila.append(valor)
        matriz.append(fila)
    return matriz

def mostrar_matriz(A):
    for fila in A:
        print("[", end=" ")
        for elemento in fila:
            print(f"{elemento:g}", end="\t")
        print("]")