# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/139xxGgIKYmugTTtbOsz6lHGUvDd7jKs1
"""

from entrada import ingresar_matriz, mostrar_matriz
from operaciones_matrices import *
from menu import mostrar_menu

def ejecutar():
    while True:
        opcion = mostrar_menu()

        if opcion == 5:
            print("Saliendo del programa...")
            break

        print(f"\n--- Preparando datos para Opción {opcion} ---")
        print("Matriz A:")
        A = ingresar_matriz()
        print("Matriz B:")
        B = ingresar_matriz()

        resultado = None

        if opcion == 1:
            resultado = sumar_matrices(A, B)
            nombre = "Suma"
        elif opcion == 2:
            resultado = multiplicar_matrices(A, B)
            nombre = "Multiplicación"
        elif opcion == 3:
            resultado = hadamard_matrices(A, B)
            nombre = "Producto de Hadamard"
        elif opcion == 4:
            resultado = kronecker(A, B)
            nombre = "Producto de Kronecker"

        if resultado is None:
            print("\n[!] Error: Las dimensiones de las matrices no son compatibles para esta operación.")
        else:
            print(f"\nResultado de la {nombre}:")
            mostrar_matriz(resultado)

if __name__ == "__main__":
    ejecutar()