# -*- coding: utf-8 -*-
"""Menu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAJLgusDUtXAiIlVKz0X_X3g0lqg7LaX
"""

def mostrar_menu():
    print("\n" + "="*35)
    print("   MENU DE OPERACIONES CON MATRICES")
    print("="*35)
    print("1. Suma de matrices")
    print("2. Multiplicación de matrices")
    print("3. Producto de Hadamard")
    print("4. Producto de Kronecker")
    print("5. Salir")

    while True:
        try:
            opcion = int(input("\nSeleccione una opción: "))
            if opcion in [1, 2, 3, 4, 5]:
                return opcion
            else:
                print("Error: Opción no válida (1-5).")
        except ValueError:
            print("Error: Debe ingresar un número entero.")